### ISSUE TITLE
Cornet radius variable

### ISSUE THREAD

**Issue by staticdreams** [designatednerd/DNSCastroSegmentedControl#12]
Hello,

This isn't really a bug, but more of a feature request.
I noticed that you hardcoded the radius value. Why not just expose the divider a public property? This way we could personalize the radius ourselves:

`` CGFloat cornerRadius = (CGRectGetHeight(self.frame) / publicRadiusVariable);``

The higher the value - the more square corners will get. I'd probably submit a PR, but I'm more of a Swift person and just afraid to mess things up :)

**Comment by designatednerd** [comment]
The hard-coding was to match the behavior of the original - basically, I wanted to make sure that the corner radius was always half the height of the control itself. However, I like this as an enhancement. I'm epically swamped at the moment so it may take me a bit to add, but it's definitely a good idea.

**Comment by designatednerd** [comment]
@staticdreams This is (finally) addressed in v1.4.0. Thank you for the suggestion!

**Comment by designatednerd** [comment]
@staticdreams This is (finally) addressed in v1.4.0. Thank you for the suggestion!
