### ISSUE TITLE
Outline does not change when selecting programmatically

### ISSUE THREAD

**Issue by staticdreams** [designatednerd/DNSCastroSegmentedControl#13]
When called programmatically the selected outline does not move, only selected the icon changes selected color. 

In my case the outline should have moved the the second icon.

``programmaticSegmentedControl.setSelectedSegmentIndex(1, animated: true)``

![dnscastro](https://cloud.githubusercontent.com/assets/988705/9524267/b9697994-4ce6-11e5-91a4-327fc301f8f0.png)

**Comment by designatednerd** [comment]
D'oh! I'll take a look at what's going on here. Thanks for the heads up.

**Comment by designatednerd** [comment]
@staticdreams And this is also (finally) fixed in 1.4.0. Thank you for the heads up, and apologies for the delay!
