### ISSUE TITLE
Control does not calculate the intrinsicContentSize's width

### ISSUE THREAD

**Issue by designatednerd** [designatednerd/DNSCastroSegmentedControl#3]
After discussing #2 with @jacobvanorder, we determined that the main issue he was trying to address would be solved by automatically calculating the intrinsic width of the control based on length of strings, which is not done right now.

**Comment by designatednerd** [comment]
Now available as part of v1.1.1 (cc @jacobvanorder)

**Comment by jacobvanorder** [comment]
:+1:
