### ISSUE TITLE
Incorrect assert in layoutSubviews

### ISSUE THREAD

**Issue by getaaron** [designatednerd/DNSCastroSegmentedControl#7]
From `layoutSubviews`:

    if (!self.choices) {
        NSAssert(@"NO", @"Cannot setup with no choices set!");
    }

However, `@"NO"` evaluates to `YES`, so the assert is never thrown.

I suggest we assert the actual condition:

    NSAssert(self.choices, @"Cannot setup with no choices set!");

This would allow us to remove the conditional.

**Comment by designatednerd** [comment]
Wow. That's a real dumb one on my part. Good catch. 

I'll take a look at all these in the next couple of days.

**Comment by designatednerd** [comment]
Fixed in 1.3.0
